---
volumes:
  data-prometheus: {}
  data-grafana: {}
  data-promsnmp: {}

networks:
  N000:
    ipam:
      config:
        - subnet: 172.20.0.0/24
  N001:
    ipam:
      config:
        - subnet: 172.20.2.0/24


services:
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    environment:
      TZ: UTC
    volumes:
      - ./container-fs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - data-prometheus:/prometheus
    stop_grace_period: 30s
    ports:
      - "9090:9090/tcp"
    networks:
      N000:
          ipv4_address: 172.20.0.3

  promsnmp:
    image: ghcr.io/pbrane/promsnmp-metrics:latest
    build:
      context: ..
      dockerfile: ./Dockerfile
    init: true
    tty: true
    stdin_open: true
    environment:
      TZ: UTC
      DISCOVERY_TZ: UTC
      PROM_DISCOVERY_API: snmp
      PROM_METRICS_API: snmp
      METRICS_REPO_API: snmp
      PROM_INV_FILE: /app/data/promsnmp-inventory.json
      PROM_ENCRYPT_KEY: Rkefv9+bd1Yawv7+hKhV8w==
      PROM_TENANT_ID: 0123456789
      PROM_SITE_ID: 0123456789
      PROM_SITE_LABEL: Chicago POP
      PROM_SITE_DESCR: Primary aggregation point in downtown Chicago
      PROM_SITE_ADDR: 350 E Cermak Rd, Chicago, IL 60616, USA
      PROM_SITE_LAT: 41.853742
      PROM_SITE_LONG: -87.618805
      CACHE_STATS_RATE_MILLIS: 15000
      CACHE_EXP_MILLIS: 300000
      CACHE_ENTRY_CNT: 10000
      DISCOVERY_CRON: "0 0 2 * * *"
      DISCOVERY_ON_START: true
      COLLECTION_INTERVAL: 30000
      SERVER_PORT: 8080
    volumes:
      - ./data/data-promsnmp/promsnmp:/app/data
    ports:
      - "8081:8080/tcp"
    networks:
      N000:
        ipv4_address: 172.20.0.4

  grafana:
    image: docker.io/grafana/grafana-oss:latest
    environment:
      TZ: UTC
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - data-grafana:/var/lib/grafana
      - ./container-fs/grafana/provisioning:/etc/grafana/provisioning/
      - ../src/main/resources/dashboards:/etc/grafana/provisioning/dashboards/json
    ports:
      - "3001:3000/tcp"
    networks:
      N000:
        ipv4_address: 172.20.0.5


  netsnmp_1_1:
    image: polinux/snmpd
    container_name: netsnmp_1_1
    hostname: netsnmp_1_1
    volumes:
      - ./container-fs/snmp/snmpd.conf:/etc/snmp/snmpd.conf
    ports:
      - "11161:161/udp"
    networks:
      N000:
        ipv4_address: 172.20.0.101

  netsnmp_1_2:
    image: polinux/snmpd
    container_name: netsnmp_1_2
    hostname: netsnmp_1_2
    volumes:
      - ./container-fs/snmp/snmpd.conf:/etc/snmp/snmpd.conf
    ports:
      - "11261:161/udp"
    networks:
      N000:
        ipv4_address: 172.20.0.102